apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: fmeserver-transact-ingress
  annotations:
    # 14 days read timeout for transact jobs
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1209600"
    {{- include "fmeserver.ingress.annotations" . | indent 4 }}
spec:
  {{- include "fmeserver.ingress.tls" . }}
  rules:
    - http:
        paths:
          - backend:
              serviceName: fmeserverweb
              servicePort: 8080
            path: /fmerest/v3/transformations/transact
          - backend:
              serviceName: fmeserverweb
              servicePort: 8080
            path: /fmerest/v3/transformations/transactjobs
          - backend:
              serviceName: fmeserverweb
              servicePort: 8080
            path: /fmerest/v3/transformations/transactdata
      {{- if .Values.deployment.useHostnameIngress }}
      host: {{ .Values.deployment.hostname }}
      {{ end }}
